### PR TITLE
First pass at 0.4.0 compatibility

### PR DESCRIPTION
**Pull request by josegonzalez**

### CODE REVIEW

**Comment by josegonzalez** [comment]
_bump_

**Comment by heichblatt** [comment]
Hello @josegonzalez,

once again, thanks for your contribution. I don't use dokku anymore, so maybe it would make sense to make your fork the main repo for the plugin? Let me know what you think, and if you agree, please let me know and change the entry in the dokku plugins list.

Cheers
heichblatt

**Comment by josegonzalez** [comment]
Actually, would you mind transferring your dokku plugins to my username? I will keep the license intact, as well as maintain attribution of the plugins to you. This will allow people who reference your repository to continue to pull a maintained repository while also letting me iterate on them.

Thanks for bearing with me :)

**Comment by heichblatt** [comment]
Sounds good to me. Just to be sure, I'd like to transfer [all my dokku-\* repos](https://github.com/search?q=user%3Aheichblatt+dokku) (6), is that OK with you?

**Comment by josegonzalez** [comment]
Works for me. I'll continue to maintain them as necessary :)

**Pull request merged**
